# Generated by Django 4.2.3 on 2023-08-02 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StdDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.IntegerField()),
                ('sname', models.CharField(max_length=30)),
                ('pwd', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'StdDB',
            },
        ),
    ]
